### ISSUE TITLE
[Portuguese] - Incorrect conjugation in pretérito-perfeito

### ISSUE THREAD

**Issue by ivanviragine** [bretttolbert/verbecc#7]
Hi!

When trying to conjugate the verb "andar", "ficar", "amar" (and maybe others) in Portuguese, we have an incorrect/buggy output:

'pretérito-perfeito': ['eu andei',
    'tu andaste',
    'ele andou',
    **'nós and)',**
    'vós andastes',
    'eles andaram'],

'pretérito-perfeito': ['eu fiquei',
    'tu ficaste',
    'ele ficou',
    **'nós fir)',**
    'vós ficastes',
    'eles ficaram'],

Sounds like a typo or something in the dictionary.

**Comment by ivanviragine** [comment]
Any news on this?

**Comment by bretttolbert** [comment]
Thank you for bringing this to my attention. Yes, this was due to some typos in the conjugation XML. I have corrected the errors with verbs like andar, ficar, amar, odiar and arguir in [this commit](https://github.com/bretttolbert/verbecc/commit/60f021d2124d5f9f819e0b8559f94e98b671f756). These changes are included in verbecc 1.7.0 / verbecc-svc 1.7.0. There's probably more typos in other verbs though. E.g. I know there's some problems with verbs like "doer" that are apparently only supposed to be conjugated for certain tenses. I will try to fix these errors as I have time. Please let me know if you find any more errors and don't hesitate to log another issue. I appreciate your interest in my software.
Thanks,
~Brett
